"use strict";angular.module("munchkins",["ngRoute"]).constant("Defaults",{TICK_RATE:250,SAVE_RATE:6e4,SAVE_LOCATION:"munchkinsSave"}).config(["$routeProvider",function(e){e.when("/buildings",{templateUrl:"views/buildings.html"}).otherwise({redirectTo:"/buildings"})}]);
"use strict";angular.module("munchkins").controller("Buildings",["Buildings","Resources",function(r,u){this.buildings=r;var e=function(){angular.forEach(r,function(r){r.locked&&(r.locked=!1,angular.forEach(r.requires.resources,function(e,n){r.locked||angular.forEach(u,function(u,a){a===n&&(r.locked=!(u.value.current>=e.value))})}))})};this.buy=function(n){var a=r[n],c=Math.pow(a.increase,a.value.current);a.value.current++,angular.forEach(a.requires.resources,function(r,e){var n=u[e];n.value.current-=r.value*c}),angular.forEach(a.provides.resources,function(r,e){var n=u[e];n.value.current++,n.rate+=r.rate}),e()}}]);
"use strict";angular.module("munchkins").controller("Game",["$interval","Defaults","Game","Buildings","Resources","Storage",function(a,e,u,n,r,t){var l=function(){u.ticks++,angular.forEach(r,function(a){a.value.current+=a.rate,a.value.limit&&(a.value.current=Math.min(a.value.current,a.value.limit))})};t.load(),a(t.save,e.SAVE_RATE),a(l,e.TICK_RATE)}]);
"use strict";angular.module("munchkins").controller("Log",function(){});
"use strict";angular.module("munchkins").controller("Resources",["Resources",function(s){this.resources=s}]);
"use strict";angular.module("munchkins").service("Storage",["$interval","Defaults","Game","Resources","Buildings",function(e,a,o,c,r){this.save=function(){console.log("Saving game");try{!function(){var e={version:1,game:{},resources:{},buildings:{}};e.game.ticks=o.ticks,angular.forEach(c,function(a,o){e.resources[o]={value:a.value}}),angular.forEach(r,function(a,o){e.buildings[o]={value:a.value,locked:a.locked}}),localStorage.setItem(a.SAVE_LOCATION,JSON.stringify(e))}()}catch(e){console.error(e)}},this.load=function(){console.log("Loading game");try{var e=JSON.parse(localStorage.getItem(a.SAVE_LOCATION));e.game=e.game||{},e.resources=e.resources||{},e.buildings=e.buildings||{},o.ticks=e.game.ticks||o.ticks,angular.forEach(e.resources,function(e,a){c[a].value=e.value}),angular.forEach(e.buildings,function(e,a){r[a].value=e.value,r[a].locked=e.locked})}catch(s){console.error(s)}}}]);
"use strict";angular.module("munchkins").value("Buildings",{collect:{name:"Collect Flowers",description:"Flowers are the staple of the Munchkin diet, collect them",locked:!1,increase:0,value:{current:0,max:0,level:0},requires:{},provides:{resources:{flowers:{value:1,rate:0}}}},meadow:{name:"Flower Meadow",description:"A naturally gorwing field of flowers",locked:!0,increase:1.1,value:{current:0,max:0,level:0},requires:{resources:{flowers:{value:100}}},provides:{resources:{flowers:{value:0,rate:.01}}}}});
"use strict";angular.module("munchkins").value("Game",{ticks:0});
"use strict";angular.module("munchkins").value("Resources",{flowers:{name:"Flowers",description:"Flowers are the staple of the Munchkin diet",value:{current:0,limit:0},rate:0}});
//# sourceMappingURL=.munchkins.js.map